name: GitHub Classroom Workflow

on: 
  push:
    branches:
      - 'submit'

jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1